class Action:
    is_valid: bool
    key: str
    value: float

    def __init__(self, cfg_str: str): ...

    def __call__(self): ...

    def dispose_special(self) -> None: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...
