from typing import Callable, List, Any

from ..Connection import Connection

ConnectionCallback = Callable[[Connection], ...]


class ShortcutKey:
    key: str
    func: ConnectionCallback
    description: str

    def __init__(self, key, description, func) -> None: ...

    def __call__(self, *args, **kwargs) -> Any: ...


class ShortcutKeyManager:
    keys_list: List[ShortcutKey]

    def __init__(self) -> None: ...

    def get_by_key(self, key: str) -> ShortcutKey: ...

    def get_by_description(self, description: str) -> ShortcutKey: ...

    def set_default_shortcut_keys(self) -> None: ...

    def set_key_by_description(self, description: str, key: str) -> None: ...

    def generate_ini(self) -> None: ...

    def load_ini(self) -> None: ...

    def set_func(self, key: str, description: str, func: ConnectionCallback) -> None: ...

    def display(self) -> None: ...

    def modify_shortcut_key(self) -> None: ...
