"""Short-lived markers for keyboard events generated by this process."""

from __future__ import annotations

from contextlib import contextmanager
from threading import RLock
from collections.abc import Iterable, Iterator

_lock = RLock()
_active: set[int] = set()


@contextmanager
def mark_injected(scan_codes: Iterable[int]) -> Iterator[None]:
    codes = {int(code) for code in scan_codes if int(code) > 0}
    with _lock:
        _active.update(codes)
    try:
        yield
    finally:
        with _lock:
            _active.difference_update(codes)


def is_injected(scan_code: int | None) -> bool:
    return scan_code is not None and scan_code in _active
