"""Typed host contract shared by extracted application mixins."""

from __future__ import annotations

from threading import Lock
from typing import Any

from src.application.config.profiles import ProfileStore
from src.application.file_loader import FileLoader
from src.application.playlist import Playlist
from src.application.track_controller import TrackController
from src.application.controller import ApplicationController
from src.core.domain.score import ParsedScore
from src.core.player.player import Player
from src.ui.cli.input.adapters import CursesInputAdapter
from src.ui.cli.screen_manager import ScreenManager
from src.ui.cli.settings.controller import SettingsController
from src.ui.cli.settings.session import SettingsSession


class ApplicationHost:
    """Attributes and callbacks supplied by the CLI composition root."""

    file_path: str
    player: Player | None
    score: ParsedScore | None
    running: bool
    display_active: bool
    last_display_time: float
    original_content: str
    stdscr: Any | None
    _failed_hotkeys: list[tuple[str, str]]
    _message: str
    _message_until: float
    _refresh_requested: bool
    _render_lock: Lock
    _keyboard_locked: bool
    _settings_requested: bool
    profile_store: ProfileStore
    hotkeys: dict[str, str]
    key_mapping: dict[str, str]
    key_mapping_scans: dict[str, dict[str, int]]
    controller: ApplicationController
    _curses_input: CursesInputAdapter | None
    screen_manager: ScreenManager
    settings_controller: SettingsController
    file_paths: list[str]
    playlist: Playlist
    file_loader: FileLoader
    track_controller: TrackController
    playlist_errors: list[str]
    playlist_focus: bool

    def _display_score(self) -> None: ...
    def _render_frame(self, stdscr: Any) -> None: ...
    def _request_refresh(self) -> None: ...
    def _flash(self, message: str, duration: float = 2.5) -> None: ...
    def _on_progress(
        self, current_line: int, total_lines: int, current_note: int, total_notes: int
    ) -> None: ...
    def _rebuild_hotkeys(self) -> None: ...
    def _stop_input_isolation(self) -> None: ...
    def _run_settings_ui(self, stdscr: Any) -> None: ...
    def reparse(self, message: str = "Score reparsed") -> None: ...

    # Playback controls exposed by the composed CLI mixins.
    def toggle_play_pause(self) -> None: ...
    def adjust_speed(self, delta: float) -> None: ...
    def adjust_arpeggio(self, delta: float) -> None: ...
    def toggle_arpeggio_auto(self) -> None: ...
    def adjust_interval(self, delta: float) -> None: ...
    def adjust_line_interval(self, delta: float) -> None: ...
    def adjust_space_interval(self, delta: float) -> None: ...
    def adjust_empty_line_interval(self, delta: float) -> None: ...
    def adjust_segment_length(self, delta: int) -> None: ...
    def toggle_sustain(self) -> None: ...
    def toggle_segment_strict(self) -> None: ...
    def toggle_loop(self) -> None: ...
    def toggle_line_loop(self) -> None: ...
    def toggle_output_lock(self) -> None: ...
    def toggle_keyboard_lock(self) -> None: ...

    # Navigation controls.
    def skip_backward(self) -> None: ...
    def skip_forward(self) -> None: ...
    def skip_backward_large(self) -> None: ...
    def skip_forward_large(self) -> None: ...
    def set_range_a(self) -> None: ...
    def set_range_b(self) -> None: ...
    def clear_range(self) -> None: ...
    def set_bookmark(self) -> None: ...
    def jump_to_bookmark(self) -> None: ...
    def jump_to_start(self) -> None: ...
    def jump_to_end(self) -> None: ...

    # File/application lifecycle controls.
    def quit(self) -> None: ...
    def save_config(self) -> None: ...
    def reload(self) -> None: ...
    def request_settings(self) -> None: ...
    def _apply_settings_session(self, session: SettingsSession) -> None: ...
