name: Build and Release

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller -F main.py

      - name: Rename executable
        run: mv dist/main.exe dist/GenshinImpactPianoPlayer.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/GenshinImpactPianoPlayer.exe

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: executable
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}-${{ github.sha }}
          release_name: Release ${{ github.run_id }}-${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/GenshinImpactPianoPlayer.exe
          asset_name: GenshinImpactPianoPlayer.exe
          asset_content_type: application/octet-stream
